# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixie', '0002_auto_20180504_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=True, upload_to='gallery/'),
        ),
    ]
